// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: flash_sale_submodule/notification.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Type    string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Status  string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *NotificationCreate) Reset() {
	*x = NotificationCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flash_sale_submodule_notification_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotificationCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationCreate) ProtoMessage() {}

func (x *NotificationCreate) ProtoReflect() protoreflect.Message {
	mi := &file_flash_sale_submodule_notification_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationCreate.ProtoReflect.Descriptor instead.
func (*NotificationCreate) Descriptor() ([]byte, []int) {
	return file_flash_sale_submodule_notification_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationCreate) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotificationCreate) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotificationCreate) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NotificationCreate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type NotificationUpt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	Status  string `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *NotificationUpt) Reset() {
	*x = NotificationUpt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flash_sale_submodule_notification_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotificationUpt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationUpt) ProtoMessage() {}

func (x *NotificationUpt) ProtoReflect() protoreflect.Message {
	mi := &file_flash_sale_submodule_notification_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationUpt.ProtoReflect.Descriptor instead.
func (*NotificationUpt) Descriptor() ([]byte, []int) {
	return file_flash_sale_submodule_notification_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationUpt) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NotificationUpt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type NotificationUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NotificationId string           `protobuf:"bytes,1,opt,name=NotificationId,proto3" json:"NotificationId,omitempty"`
	Body           *NotificationUpt `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
}

func (x *NotificationUpdate) Reset() {
	*x = NotificationUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flash_sale_submodule_notification_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotificationUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationUpdate) ProtoMessage() {}

func (x *NotificationUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_flash_sale_submodule_notification_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationUpdate.ProtoReflect.Descriptor instead.
func (*NotificationUpdate) Descriptor() ([]byte, []int) {
	return file_flash_sale_submodule_notification_proto_rawDescGZIP(), []int{2}
}

func (x *NotificationUpdate) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *NotificationUpdate) GetBody() *NotificationUpt {
	if x != nil {
		return x.Body
	}
	return nil
}

type NotificationGet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserId    string `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Type      string `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
	Status    string `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	Content   string `protobuf:"bytes,5,opt,name=Content,proto3" json:"Content,omitempty"`
	CreatedAt string `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
}

func (x *NotificationGet) Reset() {
	*x = NotificationGet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flash_sale_submodule_notification_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotificationGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationGet) ProtoMessage() {}

func (x *NotificationGet) ProtoReflect() protoreflect.Message {
	mi := &file_flash_sale_submodule_notification_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationGet.ProtoReflect.Descriptor instead.
func (*NotificationGet) Descriptor() ([]byte, []int) {
	return file_flash_sale_submodule_notification_proto_rawDescGZIP(), []int{3}
}

func (x *NotificationGet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotificationGet) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotificationGet) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotificationGet) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NotificationGet) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NotificationGet) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type NotifFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string      `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Status  string      `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	Content string      `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	Filter  *Pagination `protobuf:"bytes,4,opt,name=Filter,proto3" json:"Filter,omitempty"`
}

func (x *NotifFilter) Reset() {
	*x = NotifFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flash_sale_submodule_notification_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifFilter) ProtoMessage() {}

func (x *NotifFilter) ProtoReflect() protoreflect.Message {
	mi := &file_flash_sale_submodule_notification_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifFilter.ProtoReflect.Descriptor instead.
func (*NotifFilter) Descriptor() ([]byte, []int) {
	return file_flash_sale_submodule_notification_proto_rawDescGZIP(), []int{4}
}

func (x *NotifFilter) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotifFilter) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NotifFilter) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NotifFilter) GetFilter() *Pagination {
	if x != nil {
		return x.Filter
	}
	return nil
}

type NotificationList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Notifications []*NotificationGet `protobuf:"bytes,1,rep,name=Notifications,proto3" json:"Notifications,omitempty"`
	TotalCount    int64              `protobuf:"varint,2,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
	Limit         int32              `protobuf:"varint,3,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset        int32              `protobuf:"varint,4,opt,name=Offset,proto3" json:"Offset,omitempty"`
}

func (x *NotificationList) Reset() {
	*x = NotificationList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flash_sale_submodule_notification_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotificationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationList) ProtoMessage() {}

func (x *NotificationList) ProtoReflect() protoreflect.Message {
	mi := &file_flash_sale_submodule_notification_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationList.ProtoReflect.Descriptor instead.
func (*NotificationList) Descriptor() ([]byte, []int) {
	return file_flash_sale_submodule_notification_proto_rawDescGZIP(), []int{5}
}

func (x *NotificationList) GetNotifications() []*NotificationGet {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *NotificationList) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *NotificationList) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *NotificationList) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_flash_sale_submodule_notification_proto protoreflect.FileDescriptor

var file_flash_sale_submodule_notification_proto_rawDesc = []byte{
	0x0a, 0x27, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x5f, 0x73, 0x61, 0x6c, 0x65, 0x5f, 0x73, 0x75, 0x62,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x21, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x5f, 0x73, 0x61, 0x6c, 0x65, 0x5f, 0x73, 0x75, 0x62,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x72, 0x0a, 0x12, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x43, 0x0a, 0x0f, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x68, 0x0a, 0x12,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x04, 0x42, 0x6f,
	0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x74,
	0x52, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x22, 0x9d, 0x01, 0x0a, 0x0f, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x82, 0x01, 0x0a, 0x0b, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x29, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x9e, 0x01, 0x0a, 0x10,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x3c, 0x0a, 0x0d, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x65, 0x74, 0x52,
	0x0d, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x32, 0xc0, 0x02, 0x0a,
	0x13, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x1a, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x6f,
	0x69, 0x64, 0x12, 0x31, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x3c, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x1a, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56,
	0x6f, 0x69, 0x64, 0x12, 0x3f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x1a, 0x17, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x65, 0x74, 0x42,
	0x17, 0x5a, 0x15, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_flash_sale_submodule_notification_proto_rawDescOnce sync.Once
	file_flash_sale_submodule_notification_proto_rawDescData = file_flash_sale_submodule_notification_proto_rawDesc
)

func file_flash_sale_submodule_notification_proto_rawDescGZIP() []byte {
	file_flash_sale_submodule_notification_proto_rawDescOnce.Do(func() {
		file_flash_sale_submodule_notification_proto_rawDescData = protoimpl.X.CompressGZIP(file_flash_sale_submodule_notification_proto_rawDescData)
	})
	return file_flash_sale_submodule_notification_proto_rawDescData
}

var file_flash_sale_submodule_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_flash_sale_submodule_notification_proto_goTypes = []any{
	(*NotificationCreate)(nil), // 0: proto.NotificationCreate
	(*NotificationUpt)(nil),    // 1: proto.NotificationUpt
	(*NotificationUpdate)(nil), // 2: proto.NotificationUpdate
	(*NotificationGet)(nil),    // 3: proto.NotificationGet
	(*NotifFilter)(nil),        // 4: proto.NotifFilter
	(*NotificationList)(nil),   // 5: proto.NotificationList
	(*Pagination)(nil),         // 6: proto.Pagination
	(*GetById)(nil),            // 7: proto.GetById
	(*Void)(nil),               // 8: proto.Void
}
var file_flash_sale_submodule_notification_proto_depIdxs = []int32{
	1, // 0: proto.NotificationUpdate.Body:type_name -> proto.NotificationUpt
	6, // 1: proto.NotifFilter.Filter:type_name -> proto.Pagination
	3, // 2: proto.NotificationList.Notifications:type_name -> proto.NotificationGet
	0, // 3: proto.NotificationService.CreateNotification:input_type -> proto.NotificationCreate
	7, // 4: proto.NotificationService.DeleteNotification:input_type -> proto.GetById
	2, // 5: proto.NotificationService.UpdateNotification:input_type -> proto.NotificationUpdate
	4, // 6: proto.NotificationService.GetNotifications:input_type -> proto.NotifFilter
	7, // 7: proto.NotificationService.GetNotification:input_type -> proto.GetById
	8, // 8: proto.NotificationService.CreateNotification:output_type -> proto.Void
	8, // 9: proto.NotificationService.DeleteNotification:output_type -> proto.Void
	8, // 10: proto.NotificationService.UpdateNotification:output_type -> proto.Void
	5, // 11: proto.NotificationService.GetNotifications:output_type -> proto.NotificationList
	3, // 12: proto.NotificationService.GetNotification:output_type -> proto.NotificationGet
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_flash_sale_submodule_notification_proto_init() }
func file_flash_sale_submodule_notification_proto_init() {
	if File_flash_sale_submodule_notification_proto != nil {
		return
	}
	file_flash_sale_submodule_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_flash_sale_submodule_notification_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*NotificationCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flash_sale_submodule_notification_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*NotificationUpt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flash_sale_submodule_notification_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*NotificationUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flash_sale_submodule_notification_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*NotificationGet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flash_sale_submodule_notification_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*NotifFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flash_sale_submodule_notification_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*NotificationList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_flash_sale_submodule_notification_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flash_sale_submodule_notification_proto_goTypes,
		DependencyIndexes: file_flash_sale_submodule_notification_proto_depIdxs,
		MessageInfos:      file_flash_sale_submodule_notification_proto_msgTypes,
	}.Build()
	File_flash_sale_submodule_notification_proto = out.File
	file_flash_sale_submodule_notification_proto_rawDesc = nil
	file_flash_sale_submodule_notification_proto_goTypes = nil
	file_flash_sale_submodule_notification_proto_depIdxs = nil
}
